---
- name: Install Mysql package
  apt: name={{ item }} state=present
  with_items:
   - mysql-server
  notify:
    - mysql_secure_installation
  sudo: yes

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
    - restart mysql
  sudo: yes

- name: Start Mysql Service
  service: name=mysql state=started enabled=true
  sudo: yes
